version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5430:5432"
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
      image: redis
      container_name: redis_container
      hostname: redis
      volumes:
        - ./volumes/redisdata:/data
      environment:
          - ALLOW_EMPTY_PASSWORD=yes
      ports:
          - '6379:6379'
  redis-commander:
      depends_on:
          - redis
      container_name: redis-commander_container
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
          - REDIS_HOSTS=local:redis:6379 # note: this has to be the port the redis container exposes.
      ports:
          - "8081:8081"

volumes:
  pgdata:
    driver: local